# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: studiokg
description: Keole starter kit for Flutter projects.

# Remove this line if you wish to publish to pub.dev
publish_to: none

# Read more about Android versioning at
# https://developer.android.com/studio/publish/versioning
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  envied: any
  flutter_riverpod: any
  flutter_secure_storage: any
  http: any
  intl: any
  jwt_decoder: any
  package_info_plus: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  envied_generator: any
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700