# This is a basic workflow to help you get started with Actions
name: Format, analyze and test code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    name: Analyzing
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart pub get
      - name: Create .env.local file from GitHub secrets
        run: |
          echo "APP_DEBUG=false" >> .env
          echo "APP_BASE_URL=${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}" >> .env
          echo "APP_DEBUG_EMAIL=dev+customer@keole.net" >> .env
          echo "APP_DEBUG_PASSWORD=thicla" >> .env
      - run: dart pub run build_runner build --delete-conflicting-outputs
      # If using a localization package, uncomment this to generate translations
      - run: flutter gen-l10n
      - run: dart format ./lib
      - run: flutter analyze
      - run: flutter test
