# This is a basic workflow to help you get started with Actions
name: Generation, analysis and testing of the app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the preprod branch
  push:
    branches:
      - preprod
  pull_request:
    branches:
      - preprod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze-and-test:
    name: App analysis and testing
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Configure and build the app runtime environment
      - name: Setup app
        uses: ./.github/actions/setup-env
      # Creating a .env.local file with github secrets in the main workflow for security reasons
      - name: Generate .env.local file
        run: |
          echo "APP_BASE_URL=${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}" >> .env.local
          echo "APP_DEBUG_EMAIL=dev@keole.net" >> .env.local
          echo "APP_DEBUG_PASSWORD=password" >> .env.local
          echo "APP_DEBUG=false" >> .env.local
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env.local
      # Generate all dependencies for the app to run
      - name: Generate dependencies
        uses: ./.github/actions/generate-dependencies
      # App analyze
      - name: App analyze
        run: flutter analyze ./lib
      # App test
      - name: App test
        run: flutter test
